### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by pcnate** [tinkerscript/sqlssb#1]
I setup the demo and configured the database properly but the messages don't appear to be received. Is there a good way to check in the database that a message was sent?

**Comment by pcnate** [comment]
`reset.sql` needs to be improved.
use [master]
ensure `sqlssb` is owned by `sa`

queue names seemed to be swapped in demo

**Comment by tinkerscript** [comment]
Thanks a lot for your PR!

**Comment by pcnate** [comment]
Thanks for writing this. I have found it useful!

**Comment by tinkerscript** [comment]
Great news, I am very happy! Now I have the motivation to release new features :)

**Comment by pcnate** [comment]
FYI, git on your current machine isn't correctly tied to your github account

**Comment by tinkerscript** [comment]
Thanks again! It's fixed now.
